# Generated by Django 4.2.17 on 2024-12-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='baitul/media/videos/image2.jpg', upload_to='books/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='baitul/media/videos/image2.jpg', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
