# Generated by Django 4.2.17 on 2024-12-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_image_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('T', 'Tajwiid'), ('L', 'Lugha ya Kiarabu'), ('M', 'Alqaaidatul Madaniyyah'), ('Z', 'Masheikh Zetu'), ('U', 'Aqwaali za Ulamaa'), ('H', 'Hadith'), ('G', 'Matangazo'), ('P', 'Graphics Design'), ('N', 'Nahawul Waadhwih')], default='T', max_length=10),
        ),
    ]
