# Generated by Django 4.2.17 on 2025-03-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_book_options_alter_poster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='description',
            field=models.CharField(default='No description provided', max_length=200),
        ),
        migrations.AddField(
            model_name='poster',
            name='title',
            field=models.CharField(default='Untitled Poster', max_length=100),
        ),
    ]
